# Author: Julien Diot juliendiot@ut-biomet.org
# 2021 The University of Tokyo
#
# Description:
# This file contain the descriptions of all the command line tool's arguments


arg <- list()

# genoFile ----
arg$genoFile$flag <- '--genoFile'
arg$genoFile$help <- 'Path of the geno data file (`.vcf` or `.vcf.gz` file)'
arg$genoFile$type <- 'character'


# phenoFile ----
arg$phenoFile$flag = '--phenoFile'
arg$phenoFile$help = paste('Path of the phenotypic data file (`csv` file).',
                           'The individuals names should be on the first',
                           'columns, and no duplicate are allowed')
arg$phenoFile$type = 'character'


# pedFile ----
arg$pedFile$flag = '--pedFile'
arg$pedFile$help = paste('Path of the pedigree data file (`csv` file).',
                         'It should have 3 columns with the individual names',
                         'on the 1st, and the parents name on the 2nd and 3rd.',
                         '. No duplicate are allowed')
arg$pedFile$type = 'character'


# gwasFile ----
arg$gwasFile$flag = '--gwasFile'
arg$gwasFile$help = 'Path of the gwas result data file (json file)'
arg$gwasFile$type = 'character'


# relmatFile ----
arg$relmatFile$flag = '--relmatFile'
arg$relmatFile$help = 'path of a file relationship file generated by this engine.'
arg$relmatFile$type = 'character'


# ped-relmatFile ----
arg$ped_relmatFile$flag = '--ped-relmatFile'
arg$ped_relmatFile$help = 'path of a pedigree relationship matrix generated by the the engine.'
arg$ped_relmatFile$type = 'character'


# geno-relmatFile ----
arg$geno_relmatFile$flag = '--geno-relmatFile'
arg$geno_relmatFile$help = 'path of a genomic relationship matrix generated by the the engine.'
arg$geno_relmatFile$type = 'character'


# outFile ----
arg$outFile$flag = '--outFile'
arg$outFile$help = 'Path of the file where to save the results'
arg$outFile$type = 'character'


# adj-method ----
arg$adj_method$flag = '--adj-method'
arg$adj_method$default = 'bonferroni'
arg$adj_method$help = paste0('p-value correction method: "holm", "hochberg", "bonferroni", "BH", "BY", "fdr", "none". Default: ', arg$adj_method$default, '. (see https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/p.adjust for more details)')
arg$adj_method$type = 'character'


# combine-method ----
arg$combine_method$flag = '--combine-method'
arg$combine_method$default = 'Legarra'
arg$combine_method$help = paste0('method to use, either "Legarra" or "Martini"',
                                 ' The default is:', arg$combine_method$default)
arg$combine_method$type = 'character'


# thresh-p ----
arg$thresh_p$flag = '--thresh-p'
arg$thresh_p$default = 0.05
arg$thresh_p$help = paste0('p-value significant threshold (default: ',
                           arg$thresh_p$default, ')')
arg$thresh_p$type = 'double'


# filter-pAdj ----
arg$filter_pAdj$flag = '--filter-pAdj'
arg$filter_pAdj$default = 1
arg$filter_pAdj$help = 'Threshold to remove points with pAdj < filter-pAdj from the plot (default no filtering)'
arg$filter_pAdj$type = 'double'


# filter_nPoints ----
arg$filter_nPoints$flag = '--filter-nPoints'
arg$filter_nPoints$default = 1e100
arg$filter_nPoints$help = 'Threshold to keep only the filter-nPoints points with the lowest p-values for the plot (default no filtering)'
arg$filter_nPoints$type = 'double'


# filter_quant ----
arg$filter_quant$flag = '--filter-quant'
arg$filter_quant$default = 1
arg$filter_quant$help = 'Threshold to keep only the filter-quant*100 percent of the points with the lowest p-values for the plot (default no filtering)'
arg$filter_quant$type = 'double'


# test ----
arg$test$flag = '--test'
arg$test$default = 'score'
arg$test$help = paste0('Which test to use. Either `"score"`, `"wald"` or `"lrt"`. For binary phenotypes, test = `"score"` is mandatory. Default ', arg$test$default, '. For more information about this parameters see: https://www.rdocumentation.org/packages/gaston/versions/1.4.9/topics/association.test')
arg$test$type = 'character'


# fixed ----
arg$fixed$flag = '--fixed'
arg$fixed$default = 0
arg$fixed$help = paste0('Number of Principal Components to include in the model with fixed effect (for test = `"wald"` or `"lrt"`). Default value is ', arg$fixed$default, '. For more information about this parameters see: https://www.rdocumentation.org/packages/gaston/versions/1.4.9/topics/association.test')
arg$fixed$type = 'integer'


# response ----
arg$response$flag = '--response'
arg$response$default = 'quantitative'
arg$response$help = paste0('Either "quantitative" or "binary". Is the trait a quantitative or a binary phenotype? Default value is ', arg$response$default)
arg$response$type = 'character'


# trait ----
arg$trait$flag = '--trait'
arg$trait$help = 'Name of the trait to analyze. Must be a column name of the phenotypic file.'
arg$trait$type = 'character'


# thresh_maf ----
arg$thresh_maf$flag = '--thresh-maf'
arg$thresh_maf$default = 0
arg$thresh_maf$help = 'Threshold for filtering markers. Only markers with minor allele frequency > `thresh-maf` will be kept. Default: no filtering.'
arg$thresh_maf$type = 'double'


# thresh_callrate ----
arg$thresh_callrate$flag = '--thresh-callrate'
arg$thresh_callrate$default = 0
arg$thresh_callrate$help = 'Threshold for filtering markers. Only markers with a callrate > `thresh-callrate` will be kept. Default no filtering.'
arg$thresh_callrate$type = 'double'


# chr ----
arg$chr$flag = '--chr'
arg$chr$default = ""
arg$chr$help = 'Name of the chromosome to show (show all by default)'
arg$chr$type = 'character'


# no-interactive ----
arg$no_interactive$flag = '--no-interactive'
arg$no_interactive$default = FALSE
arg$no_interactive$help = 'Make the output a static png image (if not the output will be an interactive html plot)'


# from ----
arg$from$flag = '--from'
arg$from$help = 'Lower bound of the range of SNPs for which the LD is computed (`from` must be lower than `to`)'
arg$from$type = 'integer'


# to ----
arg$to$flag = '--to'
arg$to$help = 'Upper bound of the range of SNPs for which the LD is computed (the total number of SNP should be lower than 50)'
arg$to$type = 'integer'


# unknown_string ----
arg$u_string$flag = '--unknown-string'
arg$u_string$default = ''
arg$u_string$help = 'A character vector of strings which should be interpreted as "unknown parent". By default: missing value in the file.'
arg$u_string$type = 'character'


# no-header ----
arg$no_header$flag = '--no-header'
arg$no_header$default = FALSE
arg$no_header$help = paste('To specify the input file do not have a header. In any cases,',
                           'the column 1 will be interpreted as the individual id',
                           ', column 2 as the first parent, column 3 as the',
                           'second parent.')


# tau ----
arg$tau$flag = '--tau'
arg$tau$default = NULL
arg$tau$help = "tau parameter of the Martini's method"
arg$tau$type = 'double'


# omega ----
arg$omega$flag = '--omega'
arg$omega$default = NULL
arg$omega$help = "omega parameter of the Martini's method"
arg$omega$type = 'double'
